/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.iamwyc.api.hello;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-14")
public enum RequestType implements org.apache.thrift.TEnum {
  JustForFun(1),
  CodeOnly(2),
  HappyRun(3);

  private final int value;

  private RequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RequestType findByValue(int value) { 
    switch (value) {
      case 1:
        return JustForFun;
      case 2:
        return CodeOnly;
      case 3:
        return HappyRun;
      default:
        return null;
    }
  }
}
